= HB4_AddOns

== Project Objectives

* Support the creation of a custom Kitchen Design using Blender 4 (B4).
* Leverage Home Builder 4 (HB4) for components and/or techniques.
* Create reusable objects that complement or extend HB4 components.

== Strategy

* Utilize HB4's notion of Mesh origin and dimensional stability.
* Begin with simple from-scratch mesh objects in lieu of extending HB4.

== Insufficient of Off-the-Shelf B4 Dimensions

=== The Unit Cube

* Mesh Objects in B4 do not incorporate real world (aka _world-space_) values.
* X, Y and Z dimensions are expressed in a _unit dimension_.
* A unit cube is simply 1-unit wide, 1-unit deep and 1-unit tall.
* The origin is at the center of the unit cube.

Default Scale::  <x-scale = 1, y-scale = 1, z-scale = 1>

B4 Origin:: Cube Center <x=0 units, y=0 units, z=0 units>

cube's <x, y, z> vertices (in "units")::
  < 1/2 unit, 1/2 unit, 1/2 unit > +
  < 1/2 unit, 1/2 unit, -1/2 unit > +
  < 1/2 unit, -1/2 unit, 1/2 unit > +
  < 1/2 unit, -1/2 unit, -1/2 unit > +
  < -1/2 unit, 1/2 unit, 1/2 unit > +
  < -1/2 unit, 1/2 unit, -1/2 unit > +
  < -1/2 unit, -1/2 unit, 1/2 unit > +
  < -1/2 unit, -1/2 unit, -1/2 unit >

=== B4 Dimensions

When Mesh Objects are rendered, "Scale" and "Dimension" come into play. Each axis is assigned a dimensional unit and a "scale" for converting mesh object units to dimensional units.

.Example 1 - All three axes adopt 1 meter as the unit of measure.

* At scale <1, 1, 1> the unit-cube's dimension is 1m x 1m x 1m.
* At scale <1, 2, 3> the unit-cube's dimension is 1m x 2m x 3m.
* At scale <2.25, 3.5, 1> the unit-cube's dimension is 2.25m x 3.5m x 1m.

.Example 2 - X adopts 1 meter, y adopts 1 foot, z adopts 1 inch

* At scale <1, 1, 1> the unit-cube's dimension 1m x 1' x 1".
* At scale <2.25, 3.5, 1> will have dimension 2.25m x 3.5' x 1".
* In all three cases, the underlying mesh remains 1 unit x 1 unit x 1 unit".

=== Relationship between Scale and Dimension

In Example 1 and 2 above the underlying mesh object remains "1 unit x 1 unit x 1 unit".

* Changing the scale of an axis, impacts the corresponding _world-space_ dimension.
* Changing the _world-space_ dimension of an object, impacts the corresponding axis scale.

It is not possible to lock the dimension of an axis. But, it is possible to lock the scale of an axis.

=== HB4's Approach

* Establishes key parameters (e.g., width, depth, height) before creating Mesh objects.
* Create a unit Cube.
* Add a Transform Geometry Node
** Scale: (Width, Depth, Height)
** Translate: (Width/2, Depth/2, Height/2) - to adjust B4 origin to HB4 origin
** Group Output
